title: Sweta Ananth # your name (or website title) here
logo: "/images/dp.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer @ Microsoft 
  <br><br>
  #Second description 
  #<br><br>
  <a href="https://www.linkedin.com/in/sweta-ananth/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
